### ISSUE TITLE
Add a footer with some information

### ISSUE THREAD

**Issue by rainbowbreeze** [GoogleDevelopersItaly/conferencedb#4]
A footer should be added, with the following information

[Coming soon](https://github.com/GoogleDevelopersItaly/conferencedb/labels/enhancement) - [Contribute](https://github.com/GoogleDevelopersItaly/conferencedb) - Conference data is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/)

Phase 1, the footer can be at the end of the page, phase 2, it should be fixed at the bottom of the screen.

**Comment by ghost** [comment]
Done.
